/* Generated by cbindgen. Do not modify manually. */

#ifndef TRIEDB_H
#define TRIEDB_H

#pragma once

/* Warning: This file is auto-generated. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum triedb_error_t {
  Success = 0,
  InvalidPath = 1,
  InvalidAddress = 2,
  DatabaseOpenFailed = 3,
  TransactionFailed = 4,
  NullPointer = 5,
  Utf8Error = 6,
  AccountNotFound = 7,
  StorageNotFound = 8,
} triedb_error_t;

typedef struct TrieDB TrieDB;

typedef struct TrieDBTransactionRO TrieDBTransactionRO;

typedef struct TrieDBTransactionRW TrieDBTransactionRW;

typedef struct CHash {
  uint8_t bytes[32];
} CHash;

typedef struct CAddress {
  uint8_t bytes[20];
} CAddress;

typedef struct CAccount {
  uint64_t nonce;
  uint8_t balance[32];
  uint8_t storage_root[32];
  uint8_t code_hash[32];
} CAccount;

typedef struct CStorageKey {
  uint8_t bytes[32];
} CStorageKey;

typedef struct CStorageValue {
  uint8_t bytes[32];
} CStorageValue;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Opens an existing database at the given path.
 *
 * # Safety
 * - `path` must be a valid null-terminated UTF-8 string
 * - `out_db` must be a valid pointer
 * - Caller must call `triedb_close` to free resources
 */
enum triedb_error_t triedb_open(const char *path, struct TrieDB **out_db);

/**
 * Creates a new database at the given path (fails if exists).
 *
 * # Safety
 * - `path` must be a valid null-terminated UTF-8 string
 * - `out_db` must be a valid pointer
 * - Caller must call `triedb_close` to free resources
 */
enum triedb_error_t triedb_create_new(const char *path, struct TrieDB **out_db);

/**
 * Closes the database and frees resources.
 *
 * # Safety
 * - `db` must be a valid pointer from `triedb_open` or `triedb_create_new`
 * - `db` must not be used after this call
 */
enum triedb_error_t triedb_close(struct TrieDB *db);

/**
 * Gets the current state root hash.
 *
 * # Safety
 * - `db` must be a valid pointer
 * - `out_root` must be a valid pointer to a 32-byte array
 */
enum triedb_error_t triedb_state_root(const struct TrieDB *db, struct CHash *out_root);

/**
 * Gets the database size in pages.
 *
 * # Safety
 * - `db` must be a valid pointer
 * - `out_size` must be a valid pointer
 */
enum triedb_error_t triedb_size(const struct TrieDB *db, uint32_t *out_size);

/**
 * Begins a read-only transaction.
 *
 * # Safety
 * - `db` must be a valid pointer
 * - `out_tx` must be a valid pointer
 * - Caller must call `triedb_ro_commit` or `triedb_ro_free` to free resources
 */
enum triedb_error_t triedb_begin_ro(const struct TrieDB *db, struct TrieDBTransactionRO **out_tx);

/**
 * Gets an account from a read-only transaction.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `out_account` must be a valid pointer
 * - `out_exists` must be a valid pointer
 */
enum triedb_error_t triedb_ro_get_account(struct TrieDBTransactionRO *tx,
                                          const struct CAddress *address,
                                          struct CAccount *out_account,
                                          bool *out_exists);

/**
 * Gets a storage slot from a read-only transaction.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `slot` must be a valid pointer to a 32-byte array
 * - `out_value` must be a valid pointer
 * - `out_exists` must be a valid pointer
 */
enum triedb_error_t triedb_ro_get_storage(struct TrieDBTransactionRO *tx,
                                          const struct CAddress *address,
                                          const struct CStorageKey *slot,
                                          struct CStorageValue *out_value,
                                          bool *out_exists);

/**
 * Commits a read-only transaction (releases snapshot).
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `tx` must not be used after this call
 */
enum triedb_error_t triedb_ro_commit(struct TrieDBTransactionRO *tx);

/**
 * Frees a read-only transaction without committing.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `tx` must not be used after this call
 */
enum triedb_error_t triedb_ro_free(struct TrieDBTransactionRO *tx);

/**
 * Begins a read-write transaction (blocks if another RW transaction exists).
 *
 * # Safety
 * - `db` must be a valid pointer
 * - `out_tx` must be a valid pointer
 * - Caller must call `triedb_rw_commit` or `triedb_rw_rollback` to free resources
 */
enum triedb_error_t triedb_begin_rw(const struct TrieDB *db, struct TrieDBTransactionRW **out_tx);

/**
 * Gets an account from a read-write transaction.
 *
 * # Safety
 * - Same safety requirements as `triedb_ro_get_account`
 */
enum triedb_error_t triedb_rw_get_account(struct TrieDBTransactionRW *tx,
                                          const struct CAddress *address,
                                          struct CAccount *out_account,
                                          bool *out_exists);

/**
 * Sets an account in a read-write transaction.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `account` must be a valid pointer (or NULL to delete)
 */
enum triedb_error_t triedb_rw_set_account(struct TrieDBTransactionRW *tx,
                                          const struct CAddress *address,
                                          const struct CAccount *account);

/**
 * Gets a storage slot from a read-write transaction.
 *
 * # Safety
 * - Same safety requirements as `triedb_ro_get_storage`
 */
enum triedb_error_t triedb_rw_get_storage(struct TrieDBTransactionRW *tx,
                                          const struct CAddress *address,
                                          const struct CStorageKey *slot,
                                          struct CStorageValue *out_value,
                                          bool *out_exists);

/**
 * Sets a storage slot in a read-write transaction.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `slot` must be a valid pointer to a 32-byte array
 * - `value` must be a valid pointer (or NULL to delete)
 */
enum triedb_error_t triedb_rw_set_storage(struct TrieDBTransactionRW *tx,
                                          const struct CAddress *address,
                                          const struct CStorageKey *slot,
                                          const struct CStorageValue *value);

/**
 * Commits a read-write transaction (persists changes).
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `tx` must not be used after this call
 */
enum triedb_error_t triedb_rw_commit(struct TrieDBTransactionRW *tx);

/**
 * Rolls back a read-write transaction (discards changes).
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `tx` must not be used after this call
 */
enum triedb_error_t triedb_rw_rollback(struct TrieDBTransactionRW *tx);

/**
 * Returns a human-readable error message for an error code.
 *
 * # Safety
 * - Returns a static string, no need to free
 */
const char *triedb_error_message(enum triedb_error_t error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TRIEDB_H */
