/* Generated by cbindgen. Do not modify manually. */

#ifndef TRIEDB_H
#define TRIEDB_H

#pragma once

/* Warning: This file is auto-generated. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum triedb_error_t {
  Success = 0,
  InvalidPath = 1,
  InvalidAddress = 2,
  DatabaseOpenFailed = 3,
  TransactionFailed = 4,
  NullPointer = 5,
  Utf8Error = 6,
  AccountNotFound = 7,
  StorageNotFound = 8,
} triedb_error_t;

typedef struct TrieDB TrieDB;

typedef struct TrieDBOverlayState TrieDBOverlayState;

typedef struct TrieDBOverlayStateMut TrieDBOverlayStateMut;

typedef struct TrieDBOverlayedRoot TrieDBOverlayedRoot;

typedef struct TrieDBTransactionRO TrieDBTransactionRO;

typedef struct TrieDBTransactionRW TrieDBTransactionRW;

typedef struct TrieDBTransactionUpgradable TrieDBTransactionUpgradable;

typedef struct CHash {
  uint8_t bytes[32];
} CHash;

typedef struct CAddress {
  uint8_t bytes[20];
} CAddress;

typedef struct CAccount {
  uint64_t nonce;
  uint8_t balance[32];
  uint8_t storage_root[32];
  uint8_t code_hash[32];
} CAccount;

typedef struct CStorageKey {
  uint8_t bytes[32];
} CStorageKey;

typedef struct CStorageValue {
  uint8_t bytes[32];
} CStorageValue;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Opens an existing database at the given path.
 *
 * # Safety
 * - `path` must be a valid null-terminated UTF-8 string
 * - `out_db` must be a valid pointer
 * - Caller must call `triedb_close` to free resources
 */
enum triedb_error_t triedb_open(const char *path, struct TrieDB **out_db);

/**
 * Creates a new database at the given path (fails if exists).
 *
 * # Safety
 * - `path` must be a valid null-terminated UTF-8 string
 * - `out_db` must be a valid pointer
 * - Caller must call `triedb_close` to free resources
 */
enum triedb_error_t triedb_create_new(const char *path, struct TrieDB **out_db);

/**
 * Closes the database and frees resources.
 *
 * # Safety
 * - `db` must be a valid pointer from `triedb_open` or `triedb_create_new`
 * - `db` must not be used after this call
 */
enum triedb_error_t triedb_close(struct TrieDB *db);

/**
 * Gets the current state root hash.
 *
 * # Safety
 * - `db` must be a valid pointer
 * - `out_root` must be a valid pointer to a 32-byte array
 */
enum triedb_error_t triedb_state_root(const struct TrieDB *db, struct CHash *out_root);

/**
 * Gets the database size in pages.
 *
 * # Safety
 * - `db` must be a valid pointer
 * - `out_size` must be a valid pointer
 */
enum triedb_error_t triedb_size(const struct TrieDB *db, uint32_t *out_size);

/**
 * Begins a read-only transaction.
 *
 * # Safety
 * - `db` must be a valid pointer
 * - `out_tx` must be a valid pointer
 * - Caller must call `triedb_ro_commit` or `triedb_ro_free` to free resources
 */
enum triedb_error_t triedb_begin_ro(const struct TrieDB *db, struct TrieDBTransactionRO **out_tx);

/**
 * Gets an account from a read-only transaction.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `out_account` must be a valid pointer
 * - `out_exists` must be a valid pointer
 */
enum triedb_error_t triedb_ro_get_account(struct TrieDBTransactionRO *tx,
                                          const struct CAddress *address,
                                          struct CAccount *out_account,
                                          bool *out_exists);

/**
 * Gets a storage slot from a read-only transaction.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `slot` must be a valid pointer to a 32-byte array
 * - `out_value` must be a valid pointer
 * - `out_exists` must be a valid pointer
 */
enum triedb_error_t triedb_ro_get_storage(struct TrieDBTransactionRO *tx,
                                          const struct CAddress *address,
                                          const struct CStorageKey *slot,
                                          struct CStorageValue *out_value,
                                          bool *out_exists);

/**
 * Commits a read-only transaction (releases snapshot).
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `tx` must not be used after this call
 */
enum triedb_error_t triedb_ro_commit(struct TrieDBTransactionRO *tx);

/**
 * Frees a read-only transaction without committing.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `tx` must not be used after this call
 */
enum triedb_error_t triedb_ro_free(struct TrieDBTransactionRO *tx);

/**
 * Begins a read-write transaction (blocks if another RW transaction exists).
 *
 * # Safety
 * - `db` must be a valid pointer
 * - `out_tx` must be a valid pointer
 * - Caller must call `triedb_rw_commit` or `triedb_rw_rollback` to free resources
 */
enum triedb_error_t triedb_begin_rw(const struct TrieDB *db, struct TrieDBTransactionRW **out_tx);

/**
 * Gets an account from a read-write transaction.
 *
 * # Safety
 * - Same safety requirements as `triedb_ro_get_account`
 */
enum triedb_error_t triedb_rw_get_account(struct TrieDBTransactionRW *tx,
                                          const struct CAddress *address,
                                          struct CAccount *out_account,
                                          bool *out_exists);

/**
 * Sets an account in a read-write transaction.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `account` must be a valid pointer (or NULL to delete)
 */
enum triedb_error_t triedb_rw_set_account(struct TrieDBTransactionRW *tx,
                                          const struct CAddress *address,
                                          const struct CAccount *account);

/**
 * Gets a storage slot from a read-write transaction.
 *
 * # Safety
 * - Same safety requirements as `triedb_ro_get_storage`
 */
enum triedb_error_t triedb_rw_get_storage(struct TrieDBTransactionRW *tx,
                                          const struct CAddress *address,
                                          const struct CStorageKey *slot,
                                          struct CStorageValue *out_value,
                                          bool *out_exists);

/**
 * Sets a storage slot in a read-write transaction.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `slot` must be a valid pointer to a 32-byte array
 * - `value` must be a valid pointer (or NULL to delete)
 */
enum triedb_error_t triedb_rw_set_storage(struct TrieDBTransactionRW *tx,
                                          const struct CAddress *address,
                                          const struct CStorageKey *slot,
                                          const struct CStorageValue *value);

/**
 * Commits a read-write transaction (persists changes).
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `tx` must not be used after this call
 */
enum triedb_error_t triedb_rw_commit(struct TrieDBTransactionRW *tx);

/**
 * Rolls back a read-write transaction (discards changes).
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `tx` must not be used after this call
 */
enum triedb_error_t triedb_rw_rollback(struct TrieDBTransactionRW *tx);

/**
 * Begins an upgradable transaction (deferred write lock acquisition).
 * Changes are accumulated in memory until compute_root() is called.
 *
 * # Safety
 * - `db` must be a valid pointer
 * - `out_tx` must be a valid pointer
 * - Caller must call `triedb_upgradable_commit` or `triedb_upgradable_rollback` to free resources
 */
enum triedb_error_t triedb_begin_upgradable(const struct TrieDB *db,
                                            struct TrieDBTransactionUpgradable **out_tx);

/**
 * Gets an account from an upgradable transaction.
 *
 * # Safety
 * - Same safety requirements as `triedb_ro_get_account`
 */
enum triedb_error_t triedb_upgradable_get_account(struct TrieDBTransactionUpgradable *tx,
                                                  const struct CAddress *address,
                                                  struct CAccount *out_account,
                                                  bool *out_exists);

/**
 * Sets an account in an upgradable transaction.
 * Changes are accumulated in memory until compute_root() is called.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `account` must be a valid pointer (or NULL to delete)
 */
enum triedb_error_t triedb_upgradable_set_account(struct TrieDBTransactionUpgradable *tx,
                                                  const struct CAddress *address,
                                                  const struct CAccount *account);

/**
 * Gets a storage slot from an upgradable transaction.
 *
 * # Safety
 * - Same safety requirements as `triedb_ro_get_storage`
 */
enum triedb_error_t triedb_upgradable_get_storage(struct TrieDBTransactionUpgradable *tx,
                                                  const struct CAddress *address,
                                                  const struct CStorageKey *slot,
                                                  struct CStorageValue *out_value,
                                                  bool *out_exists);

/**
 * Sets a storage slot in an upgradable transaction.
 * Changes are accumulated in memory until compute_root() is called.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `slot` must be a valid pointer to a 32-byte array
 * - `value` must be a valid pointer (or NULL to delete)
 */
enum triedb_error_t triedb_upgradable_set_storage(struct TrieDBTransactionUpgradable *tx,
                                                  const struct CAddress *address,
                                                  const struct CStorageKey *slot,
                                                  const struct CStorageValue *value);

/**
 * Returns the current state root (before pending changes are applied).
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `out_root` must be a valid pointer to a 32-byte array
 */
enum triedb_error_t triedb_upgradable_state_root(const struct TrieDBTransactionUpgradable *tx,
                                                 struct CHash *out_root);

/**
 * Acquires write lock and computes the state root with pending changes applied.
 * This is the upgrade point - write lock is acquired here.
 * After calling this, must call either commit() or rollback().
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `out_root` must be a valid pointer to a 32-byte array
 */
enum triedb_error_t triedb_upgradable_compute_root(struct TrieDBTransactionUpgradable *tx,
                                                   struct CHash *out_root);

/**
 * Commits an upgradable transaction (persists changes).
 * Must call compute_root() first.
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `tx` must not be used after this call
 */
enum triedb_error_t triedb_upgradable_commit(struct TrieDBTransactionUpgradable *tx);

/**
 * Rolls back an upgradable transaction (discards changes).
 * Can be called before or after compute_root().
 *
 * # Safety
 * - `tx` must be a valid pointer
 * - `tx` must not be used after this call
 */
enum triedb_error_t triedb_upgradable_rollback(struct TrieDBTransactionUpgradable *tx);

/**
 * Creates a new mutable overlay state.
 *
 * # Safety
 * - `out_overlay` must be a valid pointer
 * - Caller must call `triedb_overlay_mut_free` to free resources
 */
enum triedb_error_t triedb_overlay_mut_new(struct TrieDBOverlayStateMut **out_overlay);

/**
 * Creates a new mutable overlay state with the specified capacity.
 *
 * # Safety
 * - `out_overlay` must be a valid pointer
 * - Caller must call `triedb_overlay_mut_free` to free resources
 */
enum triedb_error_t triedb_overlay_mut_with_capacity(uintptr_t capacity,
                                                     struct TrieDBOverlayStateMut **out_overlay);

/**
 * Inserts an account change into the mutable overlay.
 *
 * # Safety
 * - `overlay` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `account` must be a valid pointer (or NULL for tombstone/deletion)
 */
enum triedb_error_t triedb_overlay_mut_insert_account(struct TrieDBOverlayStateMut *overlay,
                                                      const struct CAddress *address,
                                                      const struct CAccount *account);

/**
 * Inserts a storage slot change into the mutable overlay.
 *
 * # Safety
 * - `overlay` must be a valid pointer
 * - `address` must be a valid pointer to a 20-byte array
 * - `slot` must be a valid pointer to a 32-byte array
 * - `value` must be a valid pointer (or NULL for tombstone/deletion)
 */
enum triedb_error_t triedb_overlay_mut_insert_storage(struct TrieDBOverlayStateMut *overlay,
                                                      const struct CAddress *address,
                                                      const struct CStorageKey *slot,
                                                      const struct CStorageValue *value);

/**
 * Returns the number of changes in the mutable overlay.
 *
 * # Safety
 * - `overlay` must be a valid pointer
 * - `out_len` must be a valid pointer
 */
enum triedb_error_t triedb_overlay_mut_len(const struct TrieDBOverlayStateMut *overlay,
                                           uintptr_t *out_len);

/**
 * Checks if the mutable overlay is empty.
 *
 * # Safety
 * - `overlay` must be a valid pointer
 * - `out_is_empty` must be a valid pointer
 */
enum triedb_error_t triedb_overlay_mut_is_empty(const struct TrieDBOverlayStateMut *overlay,
                                                bool *out_is_empty);

/**
 * Freezes a mutable overlay into an immutable overlay.
 * This consumes the mutable overlay.
 *
 * # Safety
 * - `overlay` must be a valid pointer
 * - `out_frozen` must be a valid pointer
 * - `overlay` must not be used after this call
 */
enum triedb_error_t triedb_overlay_mut_freeze(struct TrieDBOverlayStateMut *overlay,
                                              struct TrieDBOverlayState **out_frozen);

/**
 * Frees a mutable overlay without freezing.
 *
 * # Safety
 * - `overlay` must be a valid pointer
 * - `overlay` must not be used after this call
 */
enum triedb_error_t triedb_overlay_mut_free(struct TrieDBOverlayStateMut *overlay);

/**
 * Frees an immutable overlay.
 *
 * # Safety
 * - `overlay` must be a valid pointer
 * - `overlay` must not be used after this call
 */
enum triedb_error_t triedb_overlay_free(struct TrieDBOverlayState *overlay);

/**
 * Returns the number of changes in the immutable overlay.
 *
 * # Safety
 * - `overlay` must be a valid pointer
 * - `out_len` must be a valid pointer
 */
enum triedb_error_t triedb_overlay_len(const struct TrieDBOverlayState *overlay,
                                       uintptr_t *out_len);

/**
 * Checks if the immutable overlay is empty.
 *
 * # Safety
 * - `overlay` must be a valid pointer
 * - `out_is_empty` must be a valid pointer
 */
enum triedb_error_t triedb_overlay_is_empty(const struct TrieDBOverlayState *overlay,
                                            bool *out_is_empty);

/**
 * Computes the state root with overlay changes applied.
 * This is the main function for computing what the new state root would be
 * if the overlay changes were committed.
 *
 * # Safety
 * - `tx` must be a valid read-only transaction pointer
 * - `overlay` must be a valid pointer
 * - `out_root` must be a valid pointer
 */
enum triedb_error_t triedb_ro_compute_root_with_overlay(struct TrieDBTransactionRO *tx,
                                                        const struct TrieDBOverlayState *overlay,
                                                        struct TrieDBOverlayedRoot **out_root);

/**
 * Gets the root hash from an overlayed root result.
 *
 * # Safety
 * - `overlayed_root` must be a valid pointer
 * - `out_root` must be a valid pointer to a 32-byte array
 */
enum triedb_error_t triedb_overlayed_root_hash(const struct TrieDBOverlayedRoot *overlayed_root,
                                               struct CHash *out_root);

/**
 * Frees an overlayed root.
 *
 * # Safety
 * - `overlayed_root` must be a valid pointer
 * - `overlayed_root` must not be used after this call
 */
enum triedb_error_t triedb_overlayed_root_free(struct TrieDBOverlayedRoot *overlayed_root);

/**
 * Returns a human-readable error message for an error code.
 *
 * # Safety
 * - Returns a static string, no need to free
 */
const char *triedb_error_message(enum triedb_error_t error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TRIEDB_H */
